# Nome do arquivo principal (sem a extensão .java)
MAIN_CLASS = Main

# O comando 'all' compila todos os arquivos .java
all:
	javac *.java

# O comando 'run' executa a classe principal
run:
	java $(MAIN_CLASS)

# Opcional: limpa os arquivos .class gerados
clean:
	rm -f *.class